[package]
name = "cycle_combination_finder"
version = "0.1.0"
edition = "2024"

[dependencies]
qter_core = { version = "0.1.0", path = "../qter_core" }
puzzle_theory = { git = "https://github.com/qter-project/puzzle-theory" }

[lints]
workspace = true
