[[profile.default.overrides]]
filter = "binary_id(cycle_combination_solver::cube3) or binary_id(cycle_combination_solver::cube4) or binary_id(cycle_combination_solver::megaminx)"
# placeholder for later; I will need to config these to have threads
