[package]
name = "qter_core"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools.workspace = true
internment.workspace = true
pog_ans = { git = "https://github.com/qter-project/pog-ans" }
puzzle_theory.workspace = true

[lints]
workspace = true
